### ISSUE TITLE
Error: Failed to resolve:  Show in File Show in Project Structure dialog

### ISSUE THREAD

**Issue by Iamthemax** [ViksaaSkool/AwesomeSplash#12]
Error:(29, 13) Failed to resolve: com.github.ViksaaSkool:AwesomeSplash:v1.0.0
<a href="openFile:G:/MyApplication/ShwetaComputers/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by ViksaaSkool** [comment]
page not found on the link
