### ISSUE TITLE
is it possible to show icon & svg image both? 

### ISSUE THREAD

**Issue by mhemon** [ViksaaSkool/AwesomeSplash#20]
i use ur library.  but if I want to use icon & svg image both. it,s only show svg image & icon size not customizable. Only few anim ar work in icon. and I don't have any access to control svg image like if I want to hidden svg image after anim then show a icon then text it should be more better. 
Thanks :)

**Comment by ViksaaSkool** [comment]
Currently that's not possible. I have plans to update the library, I'll consider your issue when I do that.
