### ISSUE TITLE
Change "compile" to "implementation" to support new Android Studio Versions.

### ISSUE THREAD

**Issue by AhmedMaad** [ViksaaSkool/AwesomeSplash#37]
**compile** is deprecated; replace with **implementation**

Change
`compile 'com.github.ViksaaSkool:AwesomeSplash:v1.0.0'`
To
`implementation 'com.github.ViksaaSkool:AwesomeSplash:v1.0.0'`

**Comment by ViksaaSkool** [comment]
> 
> 
> **compile** is deprecated

So is this repo :) migrate to google's componenet - [here](https://developer.android.com/guide/topics/ui/splash-screen)
