### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AhmedMaad** [ViksaaSkool/AwesomeSplash#38]
In new Android versions there is no "All projects" section in the "build.gradle" file, so all you have to do is to open "settings.gradle" file inside the gradle scripts, and add your `maven { url "https://jitpack.io" }`  like this

`dependencyResolutionManagement {`
    `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)`
    `repositories {`
        `google()`
       `mavenCentral()`
       `jcenter() // Warning: this repository is going to shut down soon`
        `maven { url "https://jitpack.io" }`
   ` }`
`}`

**Comment by ViksaaSkool** [comment]
do a PR, I'll approve it :)

**Comment by AhmedMaad** [comment]
Already did :)
Thanks!
