### ISSUE TITLE
com.viksaa.sssplash.lib.R$color

### ISSUE THREAD

**Issue by bunhann** [ViksaaSkool/AwesomeSplash#4]
I got this error.
![selection_004](https://cloud.githubusercontent.com/assets/1192508/12079678/4a44d876-b274-11e5-9300-6a818690fe2d.png)
I just extend my splash activity with AwesomeSplash but it has been crash with that.

**Comment by ViksaaSkool** [comment]
Hey, thanks for your interest in my library. I'm currently very busy I have suspicions what can cause the issue, but let me get back at you in couple of days. 

Thanks for your understanding

**Comment by bunhann** [comment]
Thanks for your respond. I'm looking forward with this issue. Please let me know, if i can help anything.

**Comment by yokei15** [comment]
Hey buddy,your animation works for me good but its works with a text "Awesome splash" how to remove that text.
![screenshot_2016-01-27-10-38-21](https://cloud.githubusercontent.com/assets/14834224/12604544/81039a16-c4e2-11e5-85e4-225ec8ac1ed2.png)

**Comment by jeanlucDjeke** [comment]
Hello bunhann, i have the same issue.My application crashed on android 4.1 but works for others.Please need help

**Comment by ViksaaSkool** [comment]
[This will solve the issue.](http://stackoverflow.com/a/32236382)
