### ISSUE TITLE
How to remove Textview

### ISSUE THREAD

**Issue by yokei15** [ViksaaSkool/AwesomeSplash#5]
Hey buddy,your animation works for me good but its works with a text "Awesome splash" how to remove that text.
![screenshot_2016-01-27-10-38-21](https://cloud.githubusercontent.com/assets/14834224/12605226/09ddbf5a-c4e9-11e5-9ee7-888761e1b902.png)

**Comment by bunhann** [comment]
You can set animation duration of title.
configSplash.setAnimTitleDuration(0);

**Comment by yokei15** [comment]
Yep thanx dude its working..
