### ISSUE TITLE
api 4.1 not circular

### ISSUE THREAD

**Issue by MansoorJafari** [ViksaaSkool/AwesomeSplash#9]
Hello Mr.Viksaa Skool
I am testing in huawei y300 device and not circular effect.
can you help me.

Thank you.

**Comment by ViksaaSkool** [comment]
It's known bug and it happens in some particular devices. 
Thanks for noting that 'huawei y300' is one of them. Since I don't have the device I cannot reproduce the bug myself, but I'll do my best to resolve this issue in the upcoming releases.
